export const works = [
  {
    description: 'HaiDafam',
    images: [
      'https://bucket.bhsk.dev/dafam-1.png',
      'https://bucket.bhsk.dev/dafam-2.png',
      'https://bucket.bhsk.dev/dafam-3.png',
    ],
    techStack: ['Create-React-App', 'React', 'Typescript', 'AntDesign', 'Vercel'],
    title: 'HaiDafam Hospitality Dashboard',
    client: 'Dafam Hotel Management',
    year: '2022',
    category: 'Web',
    // url: 'https://m.haidafam.com',
  },
  {
    description: 'HaiDafam',
    images: [
      'https://bucket.bhsk.dev/haidafam-1.png',
      'https://bucket.bhsk.dev/haidafam-2.png',
      'https://bucket.bhsk.dev/haidafam-3.png',
    ],
    techStack: ['Nextjs', 'React', 'Typescript', 'TailwindCSS', 'Vercel'],
    title: 'HaiDafam Hospitality PWA',
    client: 'Dafam Hotel Management',
    year: '2022',
    category: 'Web',
    // url: 'https://m.haidafam.com',
  },
  {
    description: '',
    images: ['https://bucket.bhsk.dev/igate-1.png', 'https://bucket.bhsk.dev/igate-2.png'],
    techStack: ['Nextjs', 'React', 'Typescript', 'TailwindCSS', 'Vercel', 'Airtable', 'Motion'],
    title: 'I-Gate Ticketing Platform',
    client: 'HMIF Undip',
    year: '2023',
    category: 'Web',
  },
  {
    description: '',
    images: ['https://bucket.bhsk.dev/apimas-1.png', 'https://bucket.bhsk.dev/apimas-2.png'],
    techStack: ['Nextjs', 'React', 'Typescript', 'TailwindCSS', 'Vercel'],
    title: 'Aspiration App',
    client: 'SMK N 7 Semarang',
    year: '2021',
    category: 'Web',
  },
  {
    description: '',
    images: [
      'https://bucket.bhsk.dev/patroli-satpam-1.png',
      'https://bucket.bhsk.dev/patroli-satpam-2.png',
      'https://bucket.bhsk.dev/patroli-satpam-3.png',
    ],
    techStack: [
      'Nextjs',
      'React',
      'Typescript',
      'TailwindCSS',
      'Vercel',
      'PrismaORM',
      'PostgreSQL',
      'Flutter',
    ],
    title: 'Patroli Satpam',
    client: 'Universitas Diponegoro',
    year: '2025',
    category: 'Web, Mobile',
  },
  {
    description: '',
    images: ['https://bucket.bhsk.dev/monoxide-1.png'],
    techStack: ['Nextjs', 'React', 'Typescript', 'TailwindCSS', 'Vercel'],
    title: 'Monoxide',
    client: 'Technocorner 2022',
    year: '2025',
    category: 'Web',
  },
  {
    description: '',
    images: ['https://bucket.bhsk.dev/baleharjo-1.png', 'https://bucket.bhsk.dev/baleharjo-2.png'],
    techStack: [
      'Nextjs',
      'React',
      'Typescript',
      'TailwindCSS',
      'Vercel',
      'DrizzleORM',
      'PostgreSQL',
    ],
    title: 'Baleharjo Village Web Profile',
    client: 'Baleharjo Village',
    year: '2025',
    category: 'Web',
  },
  {
    description: '',
    images: ['https://bucket.bhsk.dev/eradika-1.png'],
    techStack: ['Nextjs', 'React', 'Typescript', 'TailwindCSS', 'Vercel', 'Firebase', 'RealtimeDB'],
    title: 'Eradika - Instagram-inspired Forum',
    client: 'PKM Unnes',
    year: '2023',
    category: 'Web',
  },
  {
    description: '',
    images: [
      'https://bucket.bhsk.dev/furniboost-1.png',
      'https://bucket.bhsk.dev/furniboost-2.png',
    ],
    techStack: ['Nextjs', 'React', 'Typescript', 'TailwindCSS', 'Vercel'],
    title: 'Meubel Commerce',
    client: 'Furniboost',
    year: '2023',
    category: 'Web',
  },
  {
    description: '',
    images: [
      'https://bucket.bhsk.dev/ios-1.png',
      'https://bucket.bhsk.dev/ios-2.png',
      'https://bucket.bhsk.dev/ios-3.png',
    ],
    techStack: ['Nextjs', 'React', 'Typescript', 'TailwindCSS', 'Vercel', 'Motion'],
    title: 'Informatics Ongoing Story',
    client: 'HMIF Undip',
    year: '2022',
    category: 'Web',
  },
  {
    description: '',
    images: ['https://bucket.bhsk.dev/ipro-1.png', 'https://bucket.bhsk.dev/ipro-2.png'],
    techStack: ['Nextjs', 'React', 'Typescript', 'TailwindCSS', 'Vercel', 'Motion'],
    title: 'Informatics Project - Company Profile',
    client: 'Ipro under HMIF Undip',
    year: '2024',
    category: 'Web',
  },
  {
    description: '',
    images: [
      'https://bucket.bhsk.dev/mulo-1.png',
      'https://bucket.bhsk.dev/mulo-2.png',
      'https://bucket.bhsk.dev/mulo-3.png',
    ],
    techStack: ['Expo', 'React Native', 'Typescript'],
    title: 'Mulo - Finance App',
    client: 'Mulo',
    year: '2023',
    category: 'Mobile',
  },
  {
    description: '',
    images: ['https://bucket.bhsk.dev/news-feed-1.png', 'https://bucket.bhsk.dev/news-feed-2.png'],
    techStack: ['Nextjs', 'React', 'Typescript'],
    title: 'NewsFeed - News App',
    client: 'Wegodev Challange',
    year: '2020',
    category: 'Web',
  },
  {
    description: '',
    images: [
      'https://bucket.bhsk.dev/warung-1.png',
      'https://bucket.bhsk.dev/warung-2.png',
      'https://bucket.bhsk.dev/warung-3.png',
    ],
    techStack: ['Nextjs', 'React', 'Typescript', 'Material-UI'],
    title: 'Warung - PWA',
    client: 'KodingWorks',
    year: '2020',
    category: 'Web',
  },
  {
    description: '',
    images: [
      'https://bucket.bhsk.dev/warung-v2-1.png',
      'https://bucket.bhsk.dev/warung-v2-2.png',
      'https://bucket.bhsk.dev/warung-v2-3.png',
    ],
    techStack: ['Nextjs', 'React', 'Typescript', 'Material-UI'],
    title: 'Warung v2 - PWA',
    client: 'KodingWorks',
    year: '2021',
    category: 'Web',
  },
  {
    description: '',
    images: [
      'https://bucket.bhsk.dev/arus-1.png',
      'https://bucket.bhsk.dev/arus-2.png',
      'https://bucket.bhsk.dev/arus-3.png',
    ],
    techStack: ['Nextjs', 'React', 'Javascript', 'Material-UI'],
    title: 'Arus - Hospital Online Queue',
    client: 'Yakkum Semarang',
    year: '2020',
    category: 'Web',
  },
  {
    description: '',
    images: [
      'https://bucket.bhsk.dev/drone-1.png',
      'https://bucket.bhsk.dev/drone-2.png',
      'https://bucket.bhsk.dev/drone-3.png',
    ],
    techStack: ['Python', 'Ardupilot & PX4', 'MissionPlanner', 'Pixhawk'],
    title: 'Autonomous Drone',
    client: 'Jentayu - URDC',
    year: '2024',
    category: 'Drone',
  },
  {
    description: '',
    images: ['https://bucket.bhsk.dev/portfolio-1.png'],
    techStack: ['Figma'],
    title: 'Oejar - Study Tracer Platform',
    client: 'Hology 4.0 UB',
    year: '2021',
    category: 'UI/UX',
  },
  {
    description: '',
    images: ['https://bucket.bhsk.dev/portfolio-2.png'],
    techStack: ['Figma'],
    title: 'EduStuff - Preloved Learning Stuff Ecommerce',
    client: 'GDSC Hackfest',
    year: '2024',
    category: 'UI/UX',
  },
  {
    description: '',
    images: ['https://bucket.bhsk.dev/portfolio-3.png'],
    techStack: ['Figma'],
    title: 'Anforcom - Landing Page',
    client: 'Anforcom HMIF Undip',
    year: '2023',
    category: 'UI/UX',
  },
  {
    description: '',
    images: ['https://bucket.bhsk.dev/portfolio-4.png'],
    techStack: ['Figma'],
    title: 'Patroli Satpam - Mobile',
    client: 'Universitas Diponegoro',
    year: '2024',
    category: 'UI/UX',
  },
  {
    description: '',
    images: ['https://bucket.bhsk.dev/portfolio-5.png'],
    techStack: ['Figma'],
    title: 'Go-Resto',
    client: 'Interaksi Manusia dan Komputer Task',
    year: '2022',
    category: 'UI/UX',
  },
  {
    description: '',
    images: ['https://bucket.bhsk.dev/portfolio-6.png'],
    techStack: ['Figma'],
    title: 'Sekitarmu',
    client: 'Gemastik',
    year: '2023',
    category: 'UI/UX',
  },
  {
    description: '',
    images: ['https://bucket.bhsk.dev/portfolio-7.png'],
    techStack: ['Figma'],
    title: 'Informatics Ongoing Story - Draft',
    client: 'HMIF Undip',
    year: '2022',
    category: 'UI/UX',
  },
  {
    description: '',
    images: ['https://bucket.bhsk.dev/ai4ceo-1.png'],
    techStack: ['Nextjs', 'React', 'Typescript', 'TailwindCSS', 'Vercel', 'Supabase', 'OpenAI'],
    title: 'AI4CEO',
    client: 'AI4CEO',
    year: '2025',
    category: 'Web',
    url: 'https://app.ai4.ceo/login',
  },
  {
    description: '',
    images: ['https://bucket.bhsk.dev/alaise-1.png'],
    techStack: ['Flutter', 'Dart', 'Firebase', 'Cloud Functions'],
    title: 'Alaise By The Lake Point of Sales App',
    client: 'Alaise By The Lake',
    year: '2024',
    category: 'Mobile',
  },
  {
    description: '',
    images: ['https://bucket.bhsk.dev/delivery-chatbot-1.png'],
    techStack: [
      'Node.js',
      'Express',
      'TypeScript',
      'WhatsApp Business API',
      'OpenAI',
      'PostgreSQL',
    ],
    title: "Delovery's Omnichannel Marketing Chatbot",
    client: 'Delovery',
    year: '2025',
    category: 'Web',
  },
  {
    description: '',
    images: ['https://bucket.bhsk.dev/delivery-chatpanel-1.png'],
    techStack: [
      'Next.js',
      'React',
      'TypeScript',
      'Chatwoot',
      'Custom Modifications',
      'TailwindCSS',
    ],
    title: "Delovery's Omnichannel Marketing Chatpanel",
    client: 'Delovery',
    year: '2025',
    category: 'Web',
  },
  {
    description: '',
    images: ['https://bucket.bhsk.dev/delivery-order-1.png'],
    techStack: ['Next.js', 'React', 'TypeScript', 'TailwindCSS', 'Supabase', 'Stripe'],
    title: "Delovery's Omnichannel Marketing Order Platform",
    client: 'Delovery',
    year: '2025',
    category: 'Web',
  },
];
